import React, { useRef } from 'react';
import type { Transaction, TransactionType } from '../types';

interface DataManagementProps {
  transactions: Transaction[];
  onImportTransactions: (transactions: Transaction[]) => void;
}

export const DataManagement: React.FC<DataManagementProps> = ({ transactions, onImportTransactions }) => {
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleExport = () => {
    if (transactions.length === 0) {
      alert('No transactions to export.');
      return;
    }

    const headers = ['id', 'type', 'amount', 'category', 'date', 'note'];
    const csvContent = [
      headers.join(','),
      ...transactions.map(t => [
        t.id,
        t.type,
        t.amount,
        `"${t.category.replace(/"/g, '""')}"`,
        t.date,
        `"${t.note.replace(/"/g, '""')}"`
      ].join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', 'nallamoney_transactions.csv');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleImport = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      const text = e.target?.result as string;
      if (!text) return;

      try {
        const lines = text.split('\n').filter(line => line.trim() !== '');
        if (lines.length < 2) {
          alert('CSV file is empty or missing headers.');
          return;
        }

        const headers = lines[0].split(',').map(h => h.trim());
        const expectedHeaders = ['id', 'type', 'amount', 'category', 'date', 'note'];
        
        const isValidHeader = expectedHeaders.every(h => headers.includes(h));
        if (!isValidHeader) {
          alert('Invalid CSV format. Please ensure it was generated by Nalla Money.');
          return;
        }

        const parsedTransactions: Transaction[] = [];
        
        for (let i = 1; i < lines.length; i++) {
          const line = lines[i];
          let inQuotes = false;
          let currentField = '';
          const fields = [];
          
          for (let j = 0; j < line.length; j++) {
            const char = line[j];
            if (char === '"') {
              inQuotes = !inQuotes;
            } else if (char === ',' && !inQuotes) {
              fields.push(currentField);
              currentField = '';
            } else {
              currentField += char;
            }
          }
          fields.push(currentField);

          if (fields.length !== expectedHeaders.length) continue;

          parsedTransactions.push({
            id: fields[headers.indexOf('id')],
            type: fields[headers.indexOf('type')] as TransactionType,
            amount: parseFloat(fields[headers.indexOf('amount')]),
            category: fields[headers.indexOf('category')],
            date: fields[headers.indexOf('date')],
            note: fields[headers.indexOf('note')]
          });
        }

        onImportTransactions(parsedTransactions);
        alert(`Successfully imported ${parsedTransactions.length} transactions.`);
      } catch (error) {
        console.error("Error parsing CSV", error);
        alert('Failed to parse the CSV file.');
      }
      
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="glass-panel" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
      <h3 className="section-title">Data Management</h3>
      <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', margin: 0 }}>
        Export your transactions to a CSV file or import an existing backup.
      </p>
      
      <div style={{ display: 'flex', gap: '0.75rem' }}>
        <button 
          className="btn-ghost" 
          onClick={handleExport}
          style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
            <polyline points="7 10 12 15 17 10"/>
            <line x1="12" y1="15" x2="12" y2="3"/>
          </svg>
          Export CSV
        </button>
        
        <button 
          className="btn-ghost" 
          onClick={() => fileInputRef.current?.click()}
          style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
            <polyline points="17 8 12 3 7 8"/>
            <line x1="12" y1="3" x2="12" y2="15"/>
          </svg>
          Import CSV
        </button>
        <input 
          type="file" 
          accept=".csv" 
          ref={fileInputRef} 
          onChange={handleImport} 
          style={{ display: 'none' }} 
        />
      </div>
    </div>
  );
};
